# Site settings
title: Xiaobai Blog
header-img: img/home-bg.jpg
email: dx5878210@gmail.com
description: "0 0再不疯狂我们就老了"
baseurl: ""
url: "http://xiaobaiyizhi.github.io"
github_username:  xiaobaiyizhi
weibo_username: 2031623685

# Build settings
markdown: redcarpet
highlighter: pygments
permalink: pretty
paginate: 5
redcarpet：exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","fenced_code_blocks", "autolink", "tables", "strikethrough"]
