# Site settings
title: Xiaobai Blog
header-img: img/home-bg.jpg
email: dx5878210@gmail.com
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: "/blog"
url: "http://xiaobaiyizhi.github.io/blog/"
twitter_username: SBootstrap
github_username:  xiaobaiyizhi
facebook_username:  IronSummitMedia

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
